name: Automerge (if possible)

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/automerge.yml'
      - '.github/workflows/auto-release.yml'
      - '.github/dependabot.yml'
  workflow_run:
    workflows: 
      - "build and test"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    steps:
      - uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: '@dependabot merge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
