name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    name: Build & Test on ${{matrix.os}} & .NET ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        dotnet: 
          - '5.0.x'
          - '6.0.x'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Preparing nuget source
      run: dotnet nuget add source --username SkyCD --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SkyCD/index.json"                

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: '@dependabot merge'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
